// Write multithreaded program that generates the Fibonacci series. The program should work as follows: The user will enter on the command line the number of Fibonacci numbers that the program is to generate. The program then will create a separate thread that will generate the Fibonacci numbers, placing the sequence in data that is shared by the threads (an array is probably the most convenient data structure). When the thread finishes execution the parent will output the sequence generated by the child thread. Because the parent thread cannot begin outputting the Fibonacci sequence until the child thread finishes, this will require having the parent thread wait for the child thread to finish.

#include <stdio.h>
#include <stdlib.h>
#include <pthread.h>

int *fib;
int n;

void *gen_fib(void *arg);

int main(int argc, char *argv[])
{
    if (argc != 2)
    {
        printf("Usage: %s <number_of_terms>\n", argv[0]);
        return 1;
    }

    n = atoi(argv[1]);

    if (n <= 0)
    {
        printf("Please enter a positive number\n");
        return 1;
    }

    fib = (int *)malloc(n * sizeof(int));

    pthread_t tid;

    pthread_create(&tid, NULL, gen_fib, NULL);
    pthread_join(tid, NULL);

    printf("Fibonacci Series:\n");
    for (int i = 0; i < n; i++)
        printf("%d ", fib[i]);
    printf("\n");

    free(fib);
    return 0;
}

void *gen_fib(void *arg)
{
    if (n >= 1)
        fib[0] = 0;
    if (n >= 2)
        fib[1] = 1;

    for (int i = 2; i < n; i++)
        fib[i] = fib[i - 1] + fib[i - 2];

    pthread_exit(NULL);
}